version: '3.9'

services:

  app:
    build: .
    container_name: nestjs_app
    env_file:
      - ./src/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7
    container_name: redis_container
    command: redis-server --requirepass GlIt6I8nq2oEuh/LYqf7VWx/nZ+PGbctOIaIp71Krhw=
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  mongo:
    image: mongo:7
    container_name: mongo_container
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  redis_data:
  mongo_data:
